import { DoctorsDataType } from "@/app/types/doctors";

export const doctorsData: DoctorsDataType = {
  "mauro-lencioni": {
    id: "mauro-lencioni",
    name: "Dr Mauro Lencioni",
    title: "Consultant Cardiologist & Electrophysiologist",
    designation: "MBBS, MD, DM (Cardiology)",
    specialties: ["Cardiology", "Hypertension", "Catheter Ablation"],
    image: "/dd1.jpg",
    about: "Dr. Mauro Lencioni is a highly experienced consultant cardiologist and electrophysiologist with over 12 years of experience in treating complex cardiac conditions. He specializes in catheter ablation procedures and management of hypertension.",
    qualifications: [
      "MBBS from University of Medicine",
      "MD in Internal Medicine",
      "DM in Cardiology",
      "Fellowship in Cardiac Electrophysiology",
    ],
    experience: "12+ years",
    languages: ["English", "Italian", "Spanish"],
    availability: {
      days: ["Monday", "Wednesday", "Friday"],
      time: "9:00 AM - 5:00 PM",
    },
  },
  "aruna-arujuna": {
    id: "aruna-arujuna",
    name: "Dr Aruna Arujuna",
    title: "Consultant Cardiologist",
    designation: "MBBS, MD, DM (Cardiology)",
    specialties: ["Cardiology", "Ambulatory Blood Pressure Monitoring", "Electrocardiogram (ECG)"],
    image: "/dd2.jpg",
    about: "Dr. Aruna Arujuna is a consultant cardiologist with 8 years of experience specializing in ambulatory blood pressure monitoring and ECG diagnostics. She provides comprehensive cardiac care with a focus on preventive cardiology.",
    qualifications: [
      "MBBS from Medical College",
      "MD in Internal Medicine",
      "DM in Cardiology",
    ],
    experience: "8+ years",
    languages: ["English", "Hindi", "Tamil"],
    availability: {
      days: ["Tuesday", "Thursday", "Saturday"],
      time: "10:00 AM - 6:00 PM",
    },
  },
  "benjamin-brown": {
    id: "benjamin-brown",
    name: "Dr Benjamin Brown",
    title: "Consultant Cardiologist/ Electrophysiologist",
    designation: "MBBS, MD, DM (Cardiology)",
    specialties: ["Cardiology", "Atrial Fibrillation Treatment", "Electrocardiogram (ECG)"],
    image: "/dd3.jpg",
    about: "Dr. Benjamin Brown is an experienced consultant cardiologist and electrophysiologist with 18 years of expertise in atrial fibrillation treatment and advanced cardiac procedures.",
    qualifications: [
      "MBBS from Medical School",
      "MD in Internal Medicine",
      "DM in Cardiology",
      "Fellowship in Cardiac Electrophysiology",
    ],
    experience: "18+ years",
    languages: ["English"],
    availability: {
      days: ["Monday", "Tuesday", "Wednesday", "Thursday"],
      time: "8:00 AM - 4:00 PM",
    },
  },
  "anna-patel": {
    id: "anna-patel",
    name: "Dr Anna Patel",
    title: "Emergency GP",
    designation: "MBBS, MRCGP",
    specialties: ["Urgent Care", "Minor Injuries"],
    image: "/dd1.jpg",
    about: "Dr. Anna Patel is an experienced emergency GP with 7 years of experience in urgent care and minor injury management. She provides same-day access for acute health concerns.",
    qualifications: [
      "MBBS from Medical University",
      "MRCGP (Member of Royal College of General Practitioners)",
    ],
    experience: "7+ years",
    languages: ["English", "Gujarati", "Hindi"],
    availability: {
      days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
      time: "8:00 AM - 8:00 PM",
    },
  },
  "marcus-lee": {
    id: "marcus-lee",
    name: "Dr Marcus Lee",
    title: "Emergency Medicine",
    designation: "MBBS, MRCP",
    specialties: ["Triage", "Fracture assessment", "Wound care"],
    image: "/dd2.jpg",
    about: "Dr. Marcus Lee specializes in emergency medicine with 10 years of experience in triage, fracture assessment, and wound care management.",
    qualifications: [
      "MBBS from Medical College",
      "MRCP (Member of Royal College of Physicians)",
      "Diploma in Emergency Medicine",
    ],
    experience: "10+ years",
    languages: ["English", "Mandarin"],
    availability: {
      days: ["Monday", "Wednesday", "Friday", "Sunday"],
      time: "9:00 AM - 9:00 PM",
    },
  },
  "priya-nair": {
    id: "priya-nair",
    name: "Dr Priya Nair",
    title: "GP & Paediatrics Lead",
    designation: "MBBS, MRCGP, DCH",
    specialties: ["Paediatrics", "Acute Illness", "Minor Procedures"],
    image: "/dd3.jpg",
    about: "Dr. Priya Nair is a GP and Paediatrics Lead with 6 years of experience, specializing in paediatric care, acute illness management, and minor procedures.",
    qualifications: [
      "MBBS from Medical University",
      "MRCGP",
      "DCH (Diploma in Child Health)",
    ],
    experience: "6+ years",
    languages: ["English", "Malayalam", "Hindi"],
    availability: {
      days: ["Tuesday", "Thursday", "Saturday"],
      time: "9:00 AM - 5:00 PM",
    },
  },
  "oliver-grant": {
    id: "oliver-grant",
    name: "Dr Oliver Grant",
    title: "Orthopaedic Practitioner",
    designation: "MBBS, MRCS, FRCS (Orth)",
    specialties: ["Musculoskeletal", "Fracture triage", "Splinting"],
    image: "/dd4.jpg",
    about: "Dr. Oliver Grant is an orthopaedic practitioner with 12 years of experience in musculoskeletal conditions, fracture triage, and splinting procedures.",
    qualifications: [
      "MBBS from Medical School",
      "MRCS (Member of Royal College of Surgeons)",
      "FRCS (Orth) - Fellowship in Orthopaedic Surgery",
    ],
    experience: "12+ years",
    languages: ["English"],
    availability: {
      days: ["Monday", "Wednesday", "Friday"],
      time: "8:00 AM - 6:00 PM",
    },
  },
  "sofia-martinez": {
    id: "sofia-martinez",
    name: "Dr Sofia Martinez",
    title: "Urgent Care Physician",
    designation: "MBBS, MRCGP",
    specialties: ["Imaging liaison", "Wound management", "Minor surgery"],
    image: "/dd5.jpg",
    about: "Dr. Sofia Martinez is an urgent care physician with 9 years of experience in imaging liaison, wound management, and minor surgical procedures.",
    qualifications: [
      "MBBS from Medical University",
      "MRCGP",
      "Diploma in Minor Surgery",
    ],
    experience: "9+ years",
    languages: ["English", "Spanish"],
    availability: {
      days: ["Tuesday", "Thursday", "Saturday", "Sunday"],
      time: "10:00 AM - 8:00 PM",
    },
  },
  "ethan-brooks": {
    id: "ethan-brooks",
    name: "Dr Ethan Brooks",
    title: "Clinical Lead - Acute Medicine",
    designation: "MBBS, MRCP, FRCP",
    specialties: ["Acute assessment", "Infection management", "Care coordination"],
    image: "/dd6.jpg",
    about: "Dr. Ethan Brooks is the Clinical Lead for Acute Medicine with 14 years of experience in acute assessment, infection management, and care coordination.",
    qualifications: [
      "MBBS from Medical College",
      "MRCP",
      "FRCP (Fellow of Royal College of Physicians)",
    ],
    experience: "14+ years",
    languages: ["English"],
    availability: {
      days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
      time: "8:00 AM - 6:00 PM",
    },
  },
  "hannah-cole": {
    id: "hannah-cole",
    name: "Dr Hannah Cole",
    title: "Consultant Physician",
    designation: "MBBS, MRCP, FRCP",
    specialties: ["Long-term condition management", "Geriatrics"],
    image: "/dd1.jpg",
    about: "Dr. Hannah Cole is a consultant physician with 15 years of experience specializing in long-term condition management and geriatric care.",
    qualifications: [
      "MBBS from Medical University",
      "MRCP",
      "FRCP",
      "Diploma in Geriatric Medicine",
    ],
    experience: "15+ years",
    languages: ["English"],
    availability: {
      days: ["Monday", "Wednesday", "Friday"],
      time: "9:00 AM - 5:00 PM",
    },
  },
  "samuel-okoye": {
    id: "samuel-okoye",
    name: "Dr Samuel Okoye",
    title: "Endocrinologist",
    designation: "MBBS, MRCP, FRCP (Endocrinology)",
    specialties: ["Diabetes", "Hormonal disorders", "Metabolic health"],
    image: "/dd2.jpg",
    about: "Dr. Samuel Okoye is an endocrinologist with 11 years of experience in diabetes management, hormonal disorders, and metabolic health.",
    qualifications: [
      "MBBS from Medical College",
      "MRCP",
      "FRCP in Endocrinology",
    ],
    experience: "11+ years",
    languages: ["English", "Igbo"],
    availability: {
      days: ["Tuesday", "Thursday", "Saturday"],
      time: "10:00 AM - 6:00 PM",
    },
  },
  "lucy-wang": {
    id: "lucy-wang",
    name: "Dr Lucy Wang",
    title: "Orthopaedic Surgeon",
    designation: "MBBS, MRCS, FRCS (Orth)",
    specialties: ["Elective surgery", "Joint replacement", "Sports injuries"],
    image: "/dd3.jpg",
    about: "Dr. Lucy Wang is an orthopaedic surgeon with 13 years of experience in elective surgery, joint replacement, and sports injury management.",
    qualifications: [
      "MBBS from Medical University",
      "MRCS",
      "FRCS (Orth)",
    ],
    experience: "13+ years",
    languages: ["English", "Mandarin"],
    availability: {
      days: ["Monday", "Wednesday", "Friday"],
      time: "8:00 AM - 6:00 PM",
    },
  },
  "karim-hassan": {
    id: "karim-hassan",
    name: "Dr Karim Hassan",
    title: "Physiotherapist Consultant",
    designation: "BSc (Physiotherapy), MSc, PhD",
    specialties: ["Rehabilitation", "Physiotherapy", "Post-op rehab"],
    image: "/dd4.jpg",
    about: "Dr. Karim Hassan is a physiotherapist consultant with 9 years of experience in rehabilitation, physiotherapy, and post-operative rehabilitation.",
    qualifications: [
      "BSc in Physiotherapy",
      "MSc in Advanced Physiotherapy",
      "PhD in Rehabilitation Sciences",
    ],
    experience: "9+ years",
    languages: ["English", "Arabic"],
    availability: {
      days: ["Tuesday", "Thursday", "Saturday"],
      time: "9:00 AM - 5:00 PM",
    },
  },
  "maria-rossi": {
    id: "maria-rossi",
    name: "Dr Maria Rossi",
    title: "Consultant Anaesthetist",
    designation: "MBBS, FRCA",
    specialties: ["Pre-op assessment", "Pain management"],
    image: "/dd5.jpg",
    about: "Dr. Maria Rossi is a consultant anaesthetist with 17 years of experience in pre-operative assessment and pain management.",
    qualifications: [
      "MBBS from Medical University",
      "FRCA (Fellow of Royal College of Anaesthetists)",
    ],
    experience: "17+ years",
    languages: ["English", "Italian"],
    availability: {
      days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
      time: "8:00 AM - 4:00 PM",
    },
  },
  "tom-edwards": {
    id: "tom-edwards",
    name: "Dr Tom Edwards",
    title: "Chronic Pain Specialist",
    designation: "MBBS, MRCP, FRCP",
    specialties: ["Chronic pain", "Multidisciplinary rehab"],
    image: "/dd6.jpg",
    about: "Dr. Tom Edwards is a chronic pain specialist with 12 years of experience in chronic pain management and multidisciplinary rehabilitation.",
    qualifications: [
      "MBBS from Medical College",
      "MRCP",
      "FRCP",
      "Diploma in Pain Medicine",
    ],
    experience: "12+ years",
    languages: ["English"],
    availability: {
      days: ["Monday", "Wednesday", "Friday"],
      time: "9:00 AM - 5:00 PM",
    },
  },
};
